<a href="https://colab.research.google.com/github/Krisss993/data-science/blob/numpy/Numpy_funkcje.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

Sprawdza, czy tablice  A  oraz  B  są równe pod względem elementów (element-wise) z ustalonym poziomem tolerancji.

In [5]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

np.allclose(A,B,0.000001)

True

Tworzy tablice wypełnione 0, 1, 255 ... o podanych wymiarach

In [6]:
A = np.zeros((4,4), dtype='int')
ones = np.ones((5,5))
rgb = np.full(fill_value=255., shape=(10,10), dtype='float')

Tworzy jednowymiarową tablicę o podanych parametrach, następnie przekształca ją w dwuwymiarową o podanym kształcie

In [ ]:
arr = np.arange(start=10, stop=100, step=1, dtype='int')
np.ndarray.reshape(arr, (9,10))

Tworzy macierz jednostkową o wymiarze 6x6

In [ ]:
e = np.eye(N=6)


Ręczne stworzenie macierzy jednostkowej o wymiarach 6x6


In [12]:
zero = np.zeros((6,6))
for i in range(zero.shape[0]):
  for j in range(zero.shape[1]):
    if i==j:
      zero[i,j] = 1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

 Tworzy jednowymiarową tablicę składającą się z 30 pseudolosowo wygenerowanych wartości z rozkładu jednostajnego nad przedziałem  [0,1) o wymiarach 3x10

In [14]:
rand = np.random.random(size=(3,10))

Tworzy dwuwymiarową tablicę o kształcie (10, 4) wartości pseudolosowo wygenerowanych ze standardowego rozkładu normalego  N(0,1) .

In [15]:
rand = np.random.randn(10,4)

N(100,5)

In [17]:
rand_100_5 = 100 + rand * np.sqrt(5)

Tworzy 6-elementowy wektor wartości od 1 do 49 włącznie.

In [ ]:
np.random.randint(low=1, high=50, size=6)

Iterując po tablicy numpy  A  element po elemencie printuje każdy element tablicy do konsoli.

In [18]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])
for i in np.nditer(A):
  print(i)

1
4
3
5
2
6


Tworzy jednowymiarową tablicę numpy (wektor) składający się z 11 równo rozmieszczonych punktów z przedziału  [0,1].

In [19]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Tworzy macierz o przekątnej głównej o liczbach od 0 do 5

In [21]:
np.diag(np.arange(6))

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])